name: The Adams Agency
favicon: null
layout_spectrum: 0.608612809330225
typography_spectrum: 0.40405741380527616
title: The Adams Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222222'
    - '#bfc0bb'
    - '#73685b'
    - '#00643a'
    - '#d12900'
  brandStrength: 0.25
  lightness: 0.4967613781336695
  saturation: 0.4658492710441351
  rhythmicContrast: 0.15201106248423457
purpose: []
